meson8: use linaro arm gcc for soft VP
1) fix undefined reference to raise

arch[-vendor][-os]-eabi:
arm-none-eabi:
  This tool chain targets for ARM architecture, has no vendor, does
  not target an operating system and complies with the ARM EABI.

arm-none-linux-gnueabi:
  This toolchain targets the ARM architecture,has no vendor, creates
  binaries that run on the Linux operating system, and uses the GNU
  EABI. It is used to target ARM-based Linux systems.

http://www.crifan.com/uboot_cross_compile_gcc_config_arm_lib1funcs_asm_undefined_reference_to_raise/

2) disable meson suspend

  undef CONFIG_AML_SUSPEND and CONFIG_CMD_SUSPEND.
  arc_power code use arc-elf32-em4-gcc toolchain